# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://bram092.github.io"
baseurl: "/bram092.github.io"

# Google tracking id
google-tracking-id: "FALSE"

#############
# HTML Head #
#############

lang: "en"
author: "Bram Birza"
title: "{ Bram Birza }"
description: "Personal website and resum√© of Bram Birza"
keywords: "birza, bram, cv, resume"
favicon: "/img/favicon.ico"
################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "Evolution shows the history of ourselves"
me-img: "/img/me.jpg"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/bram092.png?size=50"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: False
twitter-share: False
linkedin-share: True
reddit-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "bram092.github.io"

############
# Timeline #
############

events:
  - image: "/img/timeline/NIOO_logo.png"
    date: "Januari 2026 - Today"
    description: "Data specialist at NIOO"
  - image: "/img/timeline/NIOO_logo.png"
    date: "September 2025 - December 2025"
    description: "Research assistant data at NIOO"
  - image: "/img/timeline/WUR_logo.jpg"
    date: "September 2022 - July 2025"
    description: "Master Biology: Ecology & Evolution"
  - image: "/img/timeline/WUR_logo.jpg"
    date: "September 2018 - July 2022"
    description: "Bachelor Plant Sciences: Phylogenetics & Evolution"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "brambirza@outlook.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

author_blurb_image: "https://github.com/bram092.png?size=500"
author_blurb:
  "Lorum ipsum"

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/bram092"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/bram-birza/?locale=en_US"
#  - icon: "x-twitter"
#    url: "https://twitter.com/"
#  - icon: "rss"
#    url: "https://le4ker.github.io/personal-jekyll-theme/feed.xml"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Posts: "latest-post"
  Timeline: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
